services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=maytheforcebewithyou

  starwars_ELT:
    build: ./scripts
    depends_on:
      - database
 
  jupyter:
    build: ./jupyter
    ports: 
      - 8888:8888